spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/HMV
    username: postgres
    password: safira
    driver-class-name: org.postgresql.Driver

    flyway:
      baseline-on-migrate: true
