DROP TABLE tbl_analise_clinica;
DROP TABLE tbl_funcoes_vitais;
DROP TABLE tbl_paciente;

create table tbl_paciente
(
    id_paciente           bigint generated by default as IDENTITY ,
    nome                  varchar(50) NOT NULL,
    cpf                   numeric(11) NOT NULL,
    convenio              varchar(20) NOT NULL,
    cep                   numeric(8) NOT NULL,
    endereco              varchar(20) NOT NULL,
    numero                numeric(7) NOT NULL,
    bairro                varchar(30) NOT NULL,
    ddd                   numeric(3) NOT NULL,
    celular               numeric(9) NOT NULL,
    primary key (id_paciente)
);

create table tbl_funcoes_vitais
(
    id                    bigint generated by default as IDENTITY ,
    temperatura           varchar(5) NOT NULL,
    pressaoArterial       varchar(5) NOT NULL,
    batimentosCardiacos   varchar(5) NOT NULL,
    id_paciente           int not null,
    primary key (id)
);

create table tbl_analise_clinica
(
    id_analise_clinica    bigint generated by default as IDENTITY ,
    dataAnalise           date NOT NULL,
    tbl_sintomas          int not null,
    tbl_habitos          int not null,
    tbl_exames          int not null,
    id_paciente         int not null,
    primary key (id_analise_clinica)
);